[settings]
experimental = true
python_venv_auto_create = true

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[tools]
age = "latest"
usage = "latest"
uv = "latest"

[hooks]
postinstall = "mise sync python --uv"

[env]
UV_PROJECT_ENVIRONMENT = { value='{% if env.PROJECT_SLUG %}{{ env.HOME}}/.cache/uv-venvs/{{ env.PROJECT_SLUG }}{% endif %}', tools = true }
