"$schema" = 'https://starship.rs/config-schema.json'

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[gcloud]
# This is just too noisy
disabled = true
symbol = "Ô∏èüá¨Ô∏è "

[status]
disabled = false
symbol = "‚õå"

[username]
show_always = true

[ruby]
detect_variables = []

[shell]
fish_indicator = 'Û∞à∫ '
zsh_indicator = ''
bash_indicator = ''
powershell_indicator = 'Ôë†_'
unknown_indicator = '??'
style = 'cyan bold'
disabled = false
format = '[$indicator]($style)'

[pulumi]
disabled = true
