"$schema" = 'https://starship.rs/config-schema.json'

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[gcloud]
symbol = "ï¸ğŸ‡¬ï¸ "
format = "on [$symbol$project]($style) "
detect_env_vars = ["STARSHIP_SHOW_GCLOUD"]

[status]
disabled = false
symbol = "â›Œ"

[username]
show_always = true

[ruby]
detect_variables = []

[shell]
fish_indicator = 'ğŸŸ '
zsh_indicator = ''
bash_indicator = ''
powershell_indicator = 'ï‘ _'
unknown_indicator = '??'
style = 'cyan bold'
disabled = false
format = '[$indicator]($style)'

[pulumi]
disabled = true

[docker_context]
# really long paths when DOCKER_HOST is set
disabled = true

[kubernetes]
disabled = false
detect_folders = ["k8s"]
